<template>
    <!-- SIGN IN COMPONENT -->

    <div class="signin-container p-top">
        <!-- This form is from "vee-validate", not the html form. On submit it will call the method "onSubmit" and the ":validation-schema" attribute specifies that all the values in the "formSchema" is the data that needs to be validated. -->
        <Form @submit="onSubmit" :validation-schema="formSchema">

            <!-- If the data variable "type" is false then show "Sign In", otherwise show "Sign Up" for the h1 element. -->
            <h1 v-text="!type ? 'Sign In' : 'Sign Up'"></h1>

            <!-- EMAIL INPUT -->
            <div class="form-group">
                <!-- This is the email input. The name has to match the formSchema key in the data. The v-slot directive tells the Field input which of the types of information the input will need to work with. -->
                <Field name="email" :value="'dragon@gmail.com'" v-slot="{field, errors, errorMessage}">
                    <!-- This input will take the email and bind it to the field component of "vee-validate". The Bootstrap class of "is-invalid" will be applied to the input if the array of errors (generated by vee-validate) is no longer zero. -->
                    <input type="email" 
                        class="form-control" 
                        placeholder="Email"
                        v-bind="field"
                        :class="{'is-invalid': errors.length !== 0}">
                    
                    <!-- If the errors array generated by vee-validate is no longer 0, then the generated error message will appear in this p element. -->
                    <p class="input-alert" v-if="errors.length !== 0">{{errorMessage}}</p>
                </Field>
            </div>


            <!-- PASSWORD INPUT -->
            <div class="form-group">
                <!-- This is the password input. The name has to match the formSchema key in the data. The v-slot directive tells the Field input which of the types of information the input will need to work with. -->
                <Field name="password" :value="'dragons'" v-slot="{field, errors, errorMessage}">
                    <!-- This input will take the password and bind it to the field component of "vee-validate". The Bootstrap class of "is-invalid" will be applied to the input if the array of errors (generated by vee-validate) is no longer zero. -->
                    <input type="password" 
                        class="form-control" 
                        placeholder="Password"
                        v-bind="field"
                        :class="{'is-invalid': errors.length !== 0}">
                    
                    <!-- If the errors array generated by vee-validate is no longer 0, then the generated error message will appear in this p element. -->
                    <p class="input-alert" v-if="errors.length !== 0">{{errorMessage}}</p>
                </Field>
            </div>


            <!-- SUBMIT BUTTON -->
            <button type="submit" class="btn mb-3" v-text="!type ? 'Sign In' : 'Sign Up'"></button>

            <hr>

            <!-- The choice at the bottom of the form to either sign in or sign up. -->
            <div class="form-swap" @click="type = !type">
                <p>I want to <strong>sign <span v-if="type">in</span><span v-else>up</span></strong></p>
            </div>
        </Form>
    </div>

</template>




<script>
    import {Field, Form} from 'vee-validate';
    import * as yup from 'yup';

    export default {
        data() {
            return {
                // The property to decide between sign IN and sign UP.
                type: false,
                // This property is for validating form inputs with yup.
                formSchema: {
                    // For the email input, yup qualifies that it is a string, it is required, and it is in the form of a valid email.
                    email: yup.string().required("An email is required.").email("Not a valid email."),
                    // Yup qualifies the password as a string and as required.
                    password: yup.string().required("A password is required.")
                }
            }
        },
        components: {
            Field,
            Form
        },
        methods: {
            // When the sign in form is submitted. The second param is a function straight from "vee-validate" that will reset the form inputs when this method is called.
            onSubmit(values, {resetForm}) {
                if(!this.type) {
                    // If the type variable is false, the form will be for sign IN.
                    console.log(values, "SIGN IN");
                } else {
                    // If the type variable is true, the form will be for sign UP.
                    this.$store.dispatch('auth/signUp', values);
                }

                resetForm();
            }
        }
    }

</script>